"""new schema

Revision ID: 928612551234
Revises: 
Create Date: 2025-06-22 23:24:53.530738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928612551234'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('access', sa.String(length=20), nullable=True),
    sa.Column('host', sa.String(length=50), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('door', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('whitelist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('access', sa.String(length=20), nullable=True),
    sa.Column('host', sa.String(length=50), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whitelist')
    op.drop_table('user')
    op.drop_table('history')
    # ### end Alembic commands ###
